from lib2to3.pgen2 import grammar

from Greedy import greedy
from greedy_optimal import greedy_branching
from greedy_addition_chain import greedy_complete
from Greedy_worse import greedy_worst_branching
from non_overlapping_counter import count_non_overlapping
from find_substring import find_substrings

def grammar_size(grammar):
    total_size = 0
    for token_list in grammar.values():
        total_size += len(token_list)
    return total_size

def print_grammar(grammar):
    print("\n--- Final Compressed Grammar ---")
    for rule_name, token_list in grammar.items():
        # Join the list of tokens into a single continuous string
        right_hand_side = "".join(token_list)

        # Print with the nice arrow formatting
        print(f"{rule_name} --> {right_hand_side}")
    print("--------------------------------\n")
    size = grammar_size(grammar)
    print('the size of this grammar is {}'.format(size))

def unary_string(n, character='a'):
    return character * n


import math


def run_asymptotic_ratio_experiment(max_n=100):
    """
    Runs the Greedy algorithm on unary strings from n=2 to max_n.
    Calculates the ratio: size / (3 * log_3(n))
    Prints the maximum ratio encountered.
    """
    max_ratio = 0
    n_at_max_ratio = 0

    print(f"Starting experiment for n=2 to {max_n}...")
    print("--------------------------------------------------")

    for n in range(500, max_n + 1):
        string = unary_string(n)
        final_grammar = greedy(string)
        size = grammar_size(final_grammar)
        ratio = size / (3 * math.log(n, 3))
        if ratio > max_ratio:
            max_ratio = ratio
            n_at_max_ratio = n
            print(f"New Max Ratio: {max_ratio:.6f} | Found at n = {n:<5} | Grammar Size = {size}")

        if n % 1000 == 0:
            print(f"... still processing, currently at n = {n} ...")

    print("--------------------------------------------------")
    print("EXPERIMENT COMPLETE")
    print(f"Absolute Maximum Ratio: {max_ratio:.6f}")
    print(f"Occurred at string length (n): {n_at_max_ratio}")
    print("--------------------------------------------------")

    return max_ratio, n_at_max_ratio


def run_optimal_greedy(input_sequence):
    """
    Initializes the branching search and returns the absolute smallest grammar
    found across all possible tie-breaking paths.
    """
    if isinstance(input_sequence, str):
        initial_grammar = {'A0': list(input_sequence)}
    else:
        initial_grammar = {'A0': list(input_sequence)}

    all_possible_grammars = greedy_branching(initial_grammar, rule_counter=1)

    # Find the grammar with the minimum size
    best_grammar = min(all_possible_grammars, key=grammar_size)

    print(f"Explored {len(all_possible_grammars)} different tie-breaking paths.")
    return best_grammar


def run_optimal_asymptotic_experiment(max_n):
    """
    Runs the Optimal (Branching) Greedy algorithm on unary strings.
    Calculates the ratio: size / (3 * log_3(n))
    """
    max_ratio = 0
    n_at_max_ratio = 0

    print(f"Starting OPTIMAL experiment for n=2 to {max_n}...")
    print("WARNING: Branching search is exponential. This will get slow as n grows!")
    print("--------------------------------------------------")

    for n in range(1000, max_n + 1):
        string = unary_string(n)

        final_grammar = run_optimal_greedy(string)

        size = grammar_size(final_grammar)

        ratio = size / (3 * math.log(n, 3))

        if ratio > max_ratio:
            max_ratio = ratio
            n_at_max_ratio = n
            print(f"New Max Ratio: {max_ratio:.6f} | Found at n = {n:<5} | Grammar Size = {size}")

    print("--------------------------------------------------")
    print("OPTIMAL EXPERIMENT COMPLETE")
    print(f"Absolute Maximum Ratio: {max_ratio:.6f}")
    print(f"Occurred at string length (n): {n_at_max_ratio}")
    print("--------------------------------------------------")

    return max_ratio, n_at_max_ratio


def addition_chain_length(grammar):
    """
    Calculates the length of the addition chain generated by the grammar.
    """
    total_additions = 0
    for token_list in grammar.values():
        total_additions += (len(token_list) - 1)

    return total_additions


def run_addition_chain(max_n=1000):
    """
    give the size of the addition chain generated by the greedy algorithm(not the optimal greedy algorithm)
    """
    print("n      | Greedy Chain Length")
    print("----------------------------")

    for n in range(1, max_n + 1):
        string = unary_string(n)
        final_grammar = greedy_complete(string)
        chain_length = addition_chain_length(final_grammar)
        print(f"{n:<6} | {chain_length}")

    print("----------------------------")


def run_worst_greedy(input_data):
    """
    Runs the worst-case branching greedy search.
    Accepts either a raw string OR an existing grammar dictionary.
    """
    # 1. Check if the input is ALREADY a pre-compressed grammar dictionary
    if isinstance(input_data, dict):
        initial_grammar = input_data
        # If A0 and A1 exist, length is 2, so the next rule should be A2!
        starting_rule_counter = len(initial_grammar)

        # 2. Otherwise, treat it as a raw string/list and start fresh
    else:
        initial_grammar = {'A0': list(input_data)}
        starting_rule_counter = 1

    # Run the branching algorithm
    all_possible_grammars = greedy_worst_branching(initial_grammar, rule_counter=starting_rule_counter)

    # Return the worst (longest) grammar5
    worst_grammar = max(all_possible_grammars, key=addition_chain_length)

    return worst_grammar


def run_worst_ratio_experiment(max_n=30):
    max_ratio = 0
    n_at_max_ratio = 0
    print(f"Starting WORST-CASE ratio experiment for n=2 to {max_n}...")
    print("WARNING: Branching search is exponential. Keep max_n small!")
    print("--------------------------------------------------")

    for n in range(2, max_n + 1):
        string = unary_string(n)
        worst_grammar = run_worst_greedy(string)
        size = grammar_size(worst_grammar)

        ratio = size / (3 * math.log(n, 3))

        if ratio > max_ratio:
            max_ratio = ratio
            n_at_max_ratio = n
            print(f"New Max Ratio: {max_ratio:.6f} | Found at n = {n:<3} | Worst Chain Length = {size}")

    print("--------------------------------------------------")
    print("WORST-CASE EXPERIMENT COMPLETE")
    print(f"Absolute Maximum Ratio: {max_ratio:.6f}")
    print(f"Occurred at string length (n): {n_at_max_ratio}")
    print("--------------------------------------------------")

    return max_ratio, n_at_max_ratio


def fibonacci_word(i):
    if i < 1:
        raise ValueError("Index i must be 1 or greater.")
    if i == 1:
        return "b"
    if i == 2:
        return "a"

    f_minus_2 = "b"  # F_1
    f_minus_1 = "a"  # F_2
    current_f = ""

    for _ in range(3, i + 1):
        current_f = f_minus_1 + f_minus_2
        f_minus_2 = f_minus_1
        f_minus_1 = current_f

    return current_f


from collections import defaultdict


def get_max_saving_sequences(grammar):
    """
    An ultra-optimized C-engine implementation to find the maximum savings.
    Uses Unicode mapping to calculate non-overlapping counts instantly.
    """
    # 1. Map tokens to Unicode characters to unlock C-speed string methods
    token_to_char = {}
    char_to_token = {}
    next_char_id = 1

    string_rules = []

    # Convert every rule list into a native Python string
    for rule in grammar.values():
        char_list = []
        for token in rule:
            if token not in token_to_char:
                # Map the token to a single, unique Unicode character
                char = chr(next_char_id)
                token_to_char[token] = char
                char_to_token[char] = token
                next_char_id += 1
            char_list.append(token_to_char[token])

        string_rules.append("".join(char_list))

    best_sequences_chars = []
    max_savings = -1


    max_len = max((len(r) for r in string_rules), default=0)

    # 2. Search length by length, starting at pairs (L=2)
    for L in range(2, max_len + 1):

        counts = defaultdict(int)
        for rule_str in string_rules:
            for i in range(len(rule_str) - L + 1):
                counts[rule_str[i: i + L]] += 1

        candidates = [sub for sub, c in counts.items() if c >= 2]


        if not candidates:
            break


        for sub_str in candidates:
            k = sum(rule_str.count(sub_str) for rule_str in string_rules)

            if k < 2:
                continue

            current_savings = (L - 1) * k - L

            if current_savings > max_savings:
                max_savings = current_savings
                best_sequences_chars = [sub_str]
            elif current_savings == max_savings and current_savings > -1:
                best_sequences_chars.append(sub_str)
    best_sequences = [
        tuple(char_to_token[char] for char in seq)
        for seq in best_sequences_chars
    ]

    return best_sequences, max_savings


def analyze_fibonacci_first_step(fib_index):
    fib_string = fibonacci_word(fib_index)
    initial_grammar = {'A0': list(fib_string)}
    best_sequences, max_savings = get_max_saving_sequences(initial_grammar)
    best_strings = ["".join(seq) for seq in best_sequences]
    return best_strings, max_savings


def run_first_step_experiment(max_i=12):
    print("i   | Length | Max Savings | Winning Sequences (The First Step)")
    print("---------------------------------------------------------------")
    for i in range(2, max_i + 1):

        length = len(fibonacci_word(i))
        best_strings, savings = analyze_fibonacci_first_step(i)
        winners = " OR ".join(best_strings)
        print(f"F_{i:<2} | {length:<6} | {savings:<11} | {winners}")


def get_first_iteration_state(s):
    """
    Finds the substring with the maximum savings, replaces it with 'A',
    and returns the formatted string: {new_string|replaced_string}.
    """
    n = len(s)
    max_savings = -1
    best_sub = ""

    # We only need to check up to half the string's length
    for L in range(2, n // 2 + 1):
        seen = set()
        candidates = set()

        # Fast Hash-Set Sieve: Instantly find repeating substrings
        for i in range(n - L + 1):
            sub = s[i:i + L]
            if sub in seen:
                candidates.add(sub)
            else:
                seen.add(sub)

        # EARLY EXIT: If no string of length L repeats, longer ones mathematically cannot!
        if not candidates:
            break

        # Sort candidates to ensure deterministic tie-breaking (e.g., 'ab' vs 'ba')
        for sub in sorted(candidates):
            # Use C-engine for lightning-fast non-overlapping counting
            k = s.count(sub)
            if k < 2:
                continue

            savings = (L - 1) * k - L

            # Track the absolute maximum savings
            if savings > max_savings:
                max_savings = savings
                best_sub = sub

    # If no compression is possible at all
    if best_sub == "":
        return f"{{{s}|}}"

    # Apply the replacement and format the return string
    new_string = s.replace(best_sub, "C")
    return f"{{{new_string}|{best_sub}}}"


def run_first_iteration_experiment(max_n=20):
    """
    Runs the extractor for Fibonacci words up to max_n and prints the results.
    """
    print("Running Fast First-Iteration Extraction...")
    print("-" * 60)

    for i in range(10, max_n + 1):
        fib_str = fibonacci_word(i)

        # Calculate the result
        result_string = get_first_iteration_state(fib_str)

        # Since F_20 is massive (6765 chars), we print the full string exactly
        # as you requested. (If you are writing this to a file, this is perfect).
        print(f"\n--- F_{i} (Original Length: {len(fib_str)}) ---")
        print(result_string)

def precompress_for_standard_greedy(n):
    """
    Pre-compresses F_{6n-3} using P_{3n} and perfectly formats it
    into the dictionary-of-lists format required by your standard
    greedy_worst_branching algorithm.
    """
    idx_target = 6 * n - 3
    idx_p = 3 * n

    F_target = fibonacci_word(idx_target)
    F_p = fibonacci_word(idx_p)
    P_3n = F_p[:-2]

    # We split the large string exactly where P_3n appears
    parts = F_target.split(P_3n)

    a0_tokens = []

    # Rebuild the list, inserting 'A1' as a single protected token
    for i, part in enumerate(parts):
        # Add the leftover 'a' and 'b' characters individually
        a0_tokens.extend(list(part))

        # Inject the 'A1' rule token between the parts
        if i < len(parts) - 1:
            a0_tokens.append('A1')

    # Build the exact dictionary structure your original algorithm expects
    grammar = {
        'A0': a0_tokens,
        'A1': list(P_3n)
    }

    return grammar


def precompress_for_standard_greedy2(n):
    """
    Pre-compresses F_{6n-3} by mathematically executing Step 1 and Step 2.
    Step 1: Replace P_{3n} with 'A1'
    Step 2: Accounts for the Fibonacci parity flip!
            If n is odd, uses 'ab'. If n is even, uses 'ba'.
    """
    idx_target = 6 * n - 3
    idx_p = 3 * n
    idx_f = 3 * n - 3

    # 1. Generate all required Fibonacci strings
    F_target = fibonacci_word(idx_target)
    F_p = fibonacci_word(idx_p)
    P_3n = F_p[:-2]

    F_3n_minus_3 = fibonacci_word(idx_f)

    # ==========================================
    # STEP 1: Replace P_{3n} with 'A1'
    # ==========================================
    parts = F_target.split(P_3n)
    a0_step1 = []

    for i, part in enumerate(parts):
        a0_step1.extend(list(part))
        if i < len(parts) - 1:
            a0_step1.append('A1')

    # ==========================================
    # STEP 2: Replace target sequence with 'A2'
    # ==========================================
    # Handle the Parity Flip based on n
    if n % 2 != 0:  # If n is odd
        c1, c2 = 'a', 'b'
    else:  # If n is even
        c1, c2 = 'b', 'a'

    target_seq_2 = ['A1', c1, c2, 'A1', c1, c2] + list(F_3n_minus_3)
    target_len = len(target_seq_2)

    a0_step2 = []
    i = 0
    length_a0 = len(a0_step1)
    occurrences_step2 = 0

    # Fast list replacement loop
    while i < length_a0:
        # Check if the current slice matches our target sequence
        if i <= length_a0 - target_len and a0_step1[i:i + target_len] == target_seq_2:
            a0_step2.append('A2')
            occurrences_step2 += 1
            i += target_len  # Jump past the replaced sequence
        else:
            a0_step2.append(a0_step1[i])
            i += 1

    # ==========================================
    # Finalize Grammar
    # ==========================================
    grammar = {
        'A0': a0_step2,
        'A1': list(P_3n),
        'A2': target_seq_2
    }

    # Just for clean printing
    connector = f"{c1}{c2}"

    print(f"--- 2-Step Pre-Compression Complete for n={n} (F_{idx_target}) ---")
    print(f"Rule A1 created: P_{idx_p} (Length {len(P_3n)})")
    print(
        f"Rule A2 created: A1{connector}A1{connector}F_{idx_f} (Length {target_len}), Found {occurrences_step2} times")
    print(f"Current A0 length: {len(a0_step2)}\n")

    return grammar




precompressed_grammar =  precompress_for_standard_greedy2(5)
print_grammar(precompressed_grammar)
result = run_worst_greedy(precompressed_grammar)
print_grammar(result)
tte =get_max_saving_sequences(precompressed_grammar)
print(tte)


fibs =fibonacci_word(15)
rest = run_worst_greedy(fibs)
print_grammar(rest)


#run_first_iteration_experiment(21)
#run_first_step_experiment(17)
#print('F_20 | 6765   | 6105        | abaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaaba')
#print('F_21 | 10946  | 10010       | abaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaaba')
#print('F_22 | 17711  | 16329       | abaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaaba')
#for i in range(1, 16):
#   f = fibonacci_word(i)
#   print(f"for n = {i}  the number fibonacci word is {f}")


def get_fibonacci_length(i):
    """Calculates the i-th Fibonacci number (the length of F_i)."""
    if i == 1 or i == 2: return 1
    a, b = 1, 1
    for _ in range(3, i + 1):
        a, b = b, a + b
    return b







#print(f"The sequence  appears {ab_count} times ")


string = "CbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaabaababaabaababaababaabaababaabaabCabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCbaCbaCbaabaababaabaababaababaabaababaabaabCabCab|abaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaabaababaababaabaababaababaabaababaabaababaababaabaababaaba"
initial_grammar = {'A0': list(string)}
best_sequences, max_savings = get_max_saving_sequences(initial_grammar)
print(f"Best Sequences: {best_sequences}")
print(f"Max Savings: {max_savings}")
